### ISSUE TITLE
Ability to select the list of services to install

### ISSUE THREAD

**Issue by stratosgear** [pojntfx/pojde-ng#8]
Personally, I would like **not** to have any vnc services running.

But, also, as a matter of generalization, I would like to be able to select any of the services that are being installed.  In certain cases, only installing code-server, for example.

Can these be configurable?

**Comment by pojntfx** [comment]
Absolutely! The easiest way would be a way for `pojdectl` to enable/disable the relevant systemd/OpenRC services. The harder way would be to create different images for each config & their permutations - would the former be an OK solution to you? I.e. a dialog like such:

**Select services to enable**:

- [x] Cockpit
- [x] code-server
- [x] ttyd
- [ ] noVNC
- [x] JupyterLab

`[OK]`

**Comment by stratosgear** [comment]
They both have their advantages/disadvantages... :)

Obviously the "harder" way is the best way (why burden the image with unnecessary baggage if never used) but the "easier" way is also a valid-ish solution.  

From the perspective of safety (and performance etc), it is best to not have any services that you do not use, and from the perspective of efficiency it is even better if they are not part of your stack in the first place.

So in summary: I'll take the "easy" solution but my suggestion would be to fully implement the creation of custom images.  The current `pojntfx/pojde` image is already close to 2.5GB!!!

**EDIT**: To add that, I took a look in your repo at the creation of a custom image, and indeed, given the current implementation, this will require quite some refactoring, thus indeed, this is the harder solution to this issue.  But given that you've got so far already, this should be easy for you to refactor, I believe.

**Comment by pojntfx** [comment]
Thanks for your points! I agree that making it fully modular would be a neat solution; pojde V1 actually did that, but I decided against it in the V2 rewrite - "compiling" said services takes a very long time, and shipping the monolithic image prevented the need to do some pretty advanced cache cleanups (pojde V2 has a ~950 MB base image, pojde V1 was pretty close to 10+ GB with some additions - shipping an entire OS in a container is not very efficient, but with pojde V2 the layers are re-used between all instances so there should no longer be duplication).

I'll go ahead and implement the "easy" way for now; Docker isn't really compatible with another solution (one would have to push all permutations of the services, as there is no way I know of at least which makes the images modular). Manual OverlayFS changes could be an option, but would probably be quite a bit of technical debt in the future.

**Comment by pojntfx** [comment]
@stratosgear I've prepared PR #12 which adds this feature:

![image](https://user-images.githubusercontent.com/28832235/122467793-3fbb3700-cfbb-11eb-954f-c3c695af40c4.png)

To upgrade, run:

```shell
pojdectl upgrade-pojdectl
pojdectl apply <myinstance> <myfirstport> -f -u -r
```
